# Create a 3×3 array and extract:
 The first row, last column, The element in the second row, third column

In [1]:
import numpy as np

In [3]:
arr = np.random.random((3,3))
print(arr)

[[0.40733822 0.3616342  0.23228803]
 [0.13944818 0.6108746  0.63385144]
 [0.503825   0.40992635 0.92913942]]
