# Generate a 4×4 array with random integers between 10 and 99.

In [2]:
import numpy as np

In [4]:
arr = np.random.randint(10,100,size=(4,4))
print('Random array ',arr)

Random array  [[37 80 31 78]
 [61 46 82 91]
 [93 82 27 50]
 [44 48 90 89]]
