# Learning numpy

In [2]:
import numpy as np

## Creating arrays from list

In [5]:
arr_1d = np.array([1,2,3,4,5])
print('1d array :',arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print('2d array :',arr_2d)

1d array : [1 2 3 4 5]
2d array : [[1 2 3]
 [4 5 6]]


## Lists vs array

In [ ]:
import time 
 
start = time.time()
py_pist = [i * 2 for i in range(10000000)] 
print('\nList operation time :',time.time() - start)


np_array = np.arange(10000000)
print('\nArrayoperation time :',time.time() - start)




Operation time : 0.41185784339904785

Operation time : 0.42014217376708984


## Crating arrays from scratch

In [13]:
zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((3,4))
print(ones)

full = np.full((2,3),4)
print(full)

random = np.random.random((2,3))
print(random)

sequence = np.arange(0,10,2)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[4 4 4]
 [4 4 4]]
[[0.66157387 0.80985763 0.17450467]
 [0.95037277 0.78468696 0.25500757]]
[0 2 4 6 8]


### Vector, Matrices and Tensor

In [18]:
vector = np.array([1,2,3])
print('vector :\n',vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print('matrix :\n',matrix)

tensor = np.array([ [[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]])
print('tensor:\n', tensor)

vector :
 [1 2 3]
matrix :
 [[1 2 3]
 [4 5 6]]
tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Properties of Array

In [23]:
arr = np.array([[1,2,3],
                [4,5,6]])
print('Shape :', arr.shape)
print('Dimension :', arr.ndim)
print('Size :', arr.size)
print('Data type :', arr.dtype)

Shape : (2, 3)
Dimension : 2
Size : 6
Data type : int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print('Original array :\n', arr)

reshaped = arr.reshape((3,4))
print('Reshaped array :\n', reshaped)

flattend = reshaped.flatten()
print('Flattened array :\n', flattend)

ravel = reshaped.ravel()
print('Raveled array :\n', ravel)

Original array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
