In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2  =  np.random.rand(3,3)
arr3 = np.zeros((4,4))



In [5]:
np.save('arr1.npy',arr1)
np.save('arr2.npy',arr2)
np.save('arr3.npy',arr3)

In [7]:
load_arr1  = np.load('arr1.npy')
print(load_arr1)
load_arr2  = np.load('arr2.npy')
print(load_arr2)
load_arr3  = np.load('arr3.npy')
print(load_arr3)

[[1 2 3]
 [4 5 6]]
[[0.32265955 0.87811358 0.51297387]
 [0.34734019 0.8630794  0.78730661]
 [0.50808588 0.54110869 0.95438108]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
